import { NextRequest, NextResponse } from "next/server"

export async function POST(req: NextRequest) {
  try {
    const { plan } = await req.json()

    if (!plan) {
      return NextResponse.json({ error: "No plan provided" }, { status: 400 })
    }

    const lines: string[] = []

    lines.push(plan.plan_title)
    lines.push("")
    lines.push(plan.genre + " | " + plan.skill_level + " | " + plan.daily_duration)
    lines.push("")
    lines.push("OVERVIEW")
    lines.push(plan.overview)
    lines.push("")
    lines.push("WEEKLY GOAL")
    lines.push(plan.weekly_goal)
    lines.push("")
    lines.push("=".repeat(50))
    lines.push("")

    for (const day of plan.days) {
      lines.push("DAY " + day.day_number + " - " + day.day_name.toUpperCase() + " | " + day.focus)
      lines.push(day.total_minutes + " minutes | " + day.exercises.length + " exercises")
      lines.push("")

      for (const exercise of day.exercises) {
        lines.push("  " + exercise.name + " [" + exercise.category + "] - " + exercise.duration_minutes + " min")
        lines.push("  " + exercise.description)
        lines.push("  TIP: " + exercise.tip)
        lines.push("")
      }

      lines.push("  Note: " + day.motivational_note)
      lines.push("")
      lines.push("-".repeat(50))
      lines.push("")
    }

    lines.push("Generated by FretPath | fretpath-one.vercel.app")

    const textContent = lines.join("\n")

    return new NextResponse(textContent, {
      status: 200,
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": 'attachment; filename="fretpath-practice-plan.txt"',
      },
    })

  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to export"
    return NextResponse.json({ error: message }, { status: 500 })
  }
}